data:
    name: homographies
    data_dir: revisitop1m
    train_size: 150000
    val_size: 2000
    batch_size: 32
    num_workers: 14
    homography:
        difficulty: 0.7
        max_angle: 45
    photometric:
        name: lg
model:
    name: two_view_pipeline
    extractor:
        name: extractors.dedode
        descriptor: dedode_descriptor_B.pth
        detector: https://github.com/Parskatt/DeDoDe/releases/download/v2/dedode_detector_L_v2.pth
        max_num_keypoints: 512
        force_num_keypoints: True
        detection_threshold: 0.0
        trainable: False
    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3
    matcher:
        name: matchers.lightglue
        filter_threshold: 0.1
        input_dim: 256
        flash: false
        checkpointed: true
train:
    seed: 0
    epochs: 20
    log_every_iter: 200
    eval_every_iter: 1000
    lr: 1e-4
    lr_schedule:
        start: 10
        type: exp
        on_epoch: true
        exp_div_10: 5
    plot: [5, 'gluefactory.visualization.visualize_batch.make_match_figures']
benchmarks:
    hpatches:
      eval:
        estimator: opencv
        ransac_th: 0.5
